name: AZ Text Debug + Probe (all agents)

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; else pip install requests; fi

      # ---- Debug dump (~50 newest across all threads) ----
      - name: Debug dump (~50 newest)
        env:
          AGENCY_ZOOM_USERNAME: ${{ secrets.AGENCY_ZOOM_USERNAME }}
          AGENCY_ZOOM_PASSWORD: ${{ secrets.AGENCY_ZOOM_PASSWORD }}
          TOTAL_LIMIT: "50"
          TEXT_FILTER_MODE: "all"
          FORCE_BACKFILL_MINUTES: "10080"
          SAVE_RAW_PER_PAGE: "0"
        run: |
          python ./az_sms_debug_dump.py

      # ---- API probe (calls all read-only texting endpoints) ----
      - name: Probe texting endpoints (list/detail/producer/unread)
        env:
          AGENCY_ZOOM_USERNAME: ${{ secrets.AGENCY_ZOOM_USERNAME }}
          AGENCY_ZOOM_PASSWORD: ${{ secrets.AGENCY_ZOOM_PASSWORD }}
          # Optional; used only for /producer if needed
          # AGENCY_ZOOM_USER_ID: ${{ secrets.AGENCY_ZOOM_USER_ID }}

          AZ_BASE: "https://api.agencyzoom.com"
          PAGE_SIZE: "50"
          MAX_PAGES: "2"
          SAMPLE_THREADS: "10"
          FORCE_BACKFILL_MINUTES: "10080"
          SAVE_RAW_PER_PAGE: "1"
        run: |
          python ./az_sms_text_api_probe.py

      - name: Upload debug artifacts (dump)
        uses: actions/upload-artifact@v4
        with:
          name: az-debug-out
          path: debug_out/**

      - name: Upload probe artifacts
        uses: actions/upload-artifact@v4
        with:
          name: az-probe-out
          path: probe_out/**
