name: AZ SMS Debug Dump (one-off)

on:
  workflow_dispatch:

jobs:
  dump:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Preflight check for secrets
        shell: bash
        env:
          AGENCY_ZOOM_USERNAME: ${{ secrets.AGENCY_ZOOM_USERNAME }}
          AGENCY_ZOOM_PASSWORD: ${{ secrets.AGENCY_ZOOM_PASSWORD }}
        run: |
          if [[ -z "$AGENCY_ZOOM_USERNAME" || -z "$AGENCY_ZOOM_PASSWORD" ]]; then
            echo "::error:: Missing AGENCY_ZOOM_USERNAME or AGENCY_ZOOM_PASSWORD secrets."
            exit 1
          fi
          echo "✅ Secrets verified"

      - name: Run debug dump (~50 newest)
        shell: bash
        env:
          AGENCY_ZOOM_USERNAME: ${{ secrets.AGENCY_ZOOM_USERNAME }}
          AGENCY_ZOOM_PASSWORD: ${{ secrets.AGENCY_ZOOM_PASSWORD }}
